services:
    mongodb:
        image: mongo:latest
        container_name: 'mongodb'
        volumes:
            - ./mongo-init:/docker-entrypoint-initdb.d:ro
        restart: always
        ports:
            - '27017:27017'
    examify:
        image: nikostsa27/back
        container_name: examify
        depends_on:
            - mongodb
        ports:
            - 5456:5456
        environment:
            - SPRING_DATA_MONGODB_URI=mongodb://mongodb/examify
    examify-front:
        image: front
        container_name: front
        depends_on:
            - examify
        ports:
            - 5173:5173
