spring.application.name=exams

server.port=5455

spring.jpa.hibernate.ddl-auto=update
spring.datasource.url=jdbc:mysql://${MYSQL_HOST:localhost}:3306/exams_db
spring.datasource.username=root
spring.datasource.password=2732003NT!nick
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.show-sql=true