export const SUBMIT_ANSWERS_REQUEST = 'SUBMIT_ANSWERS_REQUEST';
export const SUBMIT_ANSWERS_SUCCESS = 'SUBMIT_ANSWERS_SUCCESS';
export const SUBMIT_ANSWERS_FAILURE = 'SUBMIT_ANSWERS_FAILURE';

export const FETCH_STUDENT_SUBMISSIONS_REQUEST = 'FETCH_STUDENT_SUBMISSIONS_REQUEST';
export const FETCH_STUDENT_SUBMISSIONS_SUCCESS = 'FETCH_STUDENT_SUBMISSIONS_SUCCESS';
export const FETCH_STUDENT_SUBMISSIONS_FAILURE = 'FETCH_STUDENT_SUBMISSIONS_FAILURE';

export const FETCH_EXAM_SUBMISSIONS_REQUEST = 'FETCH_EXAM_SUBMISSIONS_REQUEST';
export const FETCH_EXAM_SUBMISSIONS_SUCCESS = 'FETCH_EXAM_SUBMISSIONS_SUCCESS';
export const FETCH_EXAM_SUBMISSIONS_FAILURE = 'FETCH_EXAM_SUBMISSIONS_FAILURE';

export const GRADE_SUBMISSION_REQUEST = 'GRADE_SUBMISSION_REQUEST';
export const GRADE_SUBMISSION_SUCCESS = 'GRADE_SUBMISSION_SUCCESS';
export const GRADE_SUBMISSION_FAILURE = 'GRADE_SUBMISSION_FAILURE';