export const FETCH_USER_COURSES_REQUEST = 'FETCH_USER_COURSES_REQUEST';
export const FETCH_USER_COURSES_SUCCESS = 'FETCH_USER_COURSES_SUCCESS';
export const FETCH_USER_COURSES_FAILURE = 'FETCH_USER_COURSES_FAILURE';