export const FETCH_ALL_EXAMS_REQUEST = "FETCH_ALL_EXAMS_REQUEST";
export const FETCH_ALL_EXAMS_SUCCESS = "FETCH_ALL_EXAMS_SUCCESS";
export const FETCH_ALL_EXAMS_FAILURE = "FETCH_ALL_EXAMS_FAILURE";

export const FETCH_USER_EXAMS_REQUEST = "FETCH_USER_EXAMS_REQUEST";
export const FETCH_USER_EXAMS_SUCCESS = "FETCH_USER_EXAMS_SUCCESS";
export const FETCH_USER_EXAMS_FAILURE = "FETCH_USER_EXAMS_FAILURE";

export const CREATE_EXAM_REQUEST = 'CREATE_EXAM_REQUEST';
export const CREATE_EXAM_SUCCESS = 'CREATE_EXAM_SUCCESS';
export const CREATE_EXAM_FAILURE = 'CREATE_EXAM_FAILURE';

export const DELETE_EXAM_REQUEST = 'DELETE_EXAM_REQUEST';
export const DELETE_EXAM_SUCCESS = 'DELETE_EXAM_SUCCESS';
export const DELETE_EXAM_FAILURE = 'DELETE_EXAM_FAILURE';

export const REGISTER_FOR_EXAM_REQUEST = 'REGISTER_FOR_EXAM_REQUEST';
export const REGISTER_FOR_EXAM_SUCCESS = 'REGISTER_FOR_EXAM_SUCCESS';
export const REGISTER_FOR_EXAM_FAILURE = 'REGISTER_FOR_EXAM_FAILURE';

export const UNREGISTER_FOR_EXAM_REQUEST = 'UNREGISTER_FOR_EXAM_REQUEST';
export const UNREGISTER_FOR_EXAM_SUCCESS = 'UNREGISTER_FOR_EXAM_SUCCESS';
export const UNREGISTER_FOR_EXAM_FAILURE = 'UNREGISTER_FOR_EXAM_FAILURE';

export const FETCH_EXAM_REQUEST = 'FETCH_EXAM_REQUEST';
export const FETCH_EXAM_SUCCESS = 'FETCH_EXAM_SUCCESS';
export const FETCH_EXAM_FAILURE = 'FETCH_EXAM_FAILURE';